###
POST http://localhost:3100/api/v1/users/new-user HTTP/1.1
Content-Type: application/json

{
    "firstname": "test2",
    "lastname": "test2",
    "email": "test2@test.com",
    "current_password": "user123"
}

###
GET http://localhost:3100/api/v1/users HTTP/1.1

###
GET http://localhost:3100/api/v1/users/6511f0cb17213cee378110c2 HTTP/1.1

###
PATCH http://localhost:3100/api/v1/users/6515d4084e338c7954999430 HTTP/1.1
Content-Type: application/json

{
    "firstname":"Test2",
    "lastname": "Test2 Lastname"
}

###
PATCH http://localhost:3100/api/v1/users/6515d4084e338c7954999430 HTTP/1.1
Content-Type: application/json

{
    "firstname":"Test2 put"
}

###
PUT http://localhost:3100/api/v1/users/6515d4084e338c7954999430 HTTP/1.1
Content-Type: application/json

{
    "firstname":"Test2 put"
}

###
DELETE http://localhost:3100/api/v1/users/6511f0cb17213cee378110c2 HTTP/1.1



###
POST http://localhost:3100/api/v1/services/new-service HTTP/1.1
Content-Type: application/json

{
    "serviceName": "Service 1.1",
    "serviceDescription": "Descripción del servicio 1.1."
}


###
GET http://localhost:3100/api/v1/services HTTP/1.1
###
GET http://localhost:3100/api/v1/services/id HTTP/1.1
###
PATCH http://localhost:3100/api/v1/services HTTP/1.1
###
DELETE http://localhost:3100/api/v1/services HTTP/1.1
